### ISSUE TITLE
Implementing an Alternative Rails-based Digital Collections Architecture,

### ISSUE THREAD

**Issue by brianmcbride** [samvera-labs/samvera-virtual-connect#12]
## Name
Jonathan Rochkind

## Institution
Science History Institute

## Title
Implementing an Alternative Rails-based Digital Collections Architecture,

## Abstract
"At the Science History Institute (formerly Chemical Heritage Foundation) we are working on re-implementing our digital collections application using a new Rails-based architecture, including sharing some building blocks in a ruby gem for those who may be interested in the same directions.  Our code is not based on hyrax or valkyrie; our persistence layer is based on postgres, ActiveRecord and metadata serialized in a JSON column. The sharable gem code already includes support for flexible derivatives; file handling using shrine; and some HTML form support for complex/repeatable fields.  It will in the future include some solr indexing support.  These components are designed for flexibility and support of performant DB usage patterns. This talk will provide a fast-paced tour of our architecture by showing example code. 

[I am open to a lightning talk if longer presentation not available]"

## Audience
Developers, DevOps and System Administrators, decision-makers for technical architecture/platform choices

## Format 
Longer presentation (approximately 20-30 minutes)

## Date preference / Availability
Open to either day

## Streaming/Recording/Archiving Permission
Yes, I consent to having my session live streamed, recorded, and archived.

**Comment by chrissyrissmeyer** [comment]
We are going to ask Jonathan if he can do this as a lightning talk, as offered, due to time constraints.

**Comment by jrochkind** [comment]
After submitting, I realized I have plenty I can say and would prefer this as a full-length talk. (especially with lightning talk time being reduced to 7 minutes from the 10 minutes I was thinking of when I proposed based on call for proposals). 

But I did offer to do a lighting talk! And y'all have accepted my talk on that basis as a lightning talk and not as a full-length presentation, so that's what I'll do!

Based on it only being 7 minutes, please edit the final line:

> ~This talk will give a tour of our architecture, and some discussion of motivations and how it's working out.~

To instead be:

"This talk will provide a fast-paced tour our architecture by showing example code. "

Thanks for your work!

**Comment by chrissyrissmeyer** [comment]
@jrochkind Updated! Thanks.
